name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      # Adicione aqui todas as variáveis que você precisa

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Create Pull Request for Auto-Merge
        if: success() && github.ref == 'refs/heads/develop'
        uses: peter-evans/create-pull-request@v5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "chore: Auto-merge develop → main"
            branch: develop        # branch de origem (source)
            base: main             # branch de destino (target)
            title: "Auto-merge from develop"
            body: "Merged automatically because all tests passed ✅"

      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}